package edu.mugi.controller;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.mugi.model.User;

@WebServlet("/create")
public class NewUserControl extends HttpServlet {
	@Override
	protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		String name = req.getParameter("name");
		String contact = req.getParameter("contact");
		String val = req.getParameter("val");
		String autoGeneratedId = "select max(userId) from user";
		String update = "update user set userContact='" + contact + "' where userName='" + name + "'";
		String delete = "delete from user where userName='" + name + "'";
		Connection con = null;
		Statement st = null;
		ResultSet rs = null;
		PrintWriter pr = null;

		try {
			Class.forName("com.mysql.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/user", "root", "root");
			st = con.createStatement();
			

			if (val.equals("CREATE")) {
				int max = 0;
				rs = st.executeQuery(autoGeneratedId);
				if (rs.next()) {
					max = rs.getInt(1);
					max++;
				}
				String create = "insert into user values('" + max + "','" + name + "','" + contact + "')";
				st.executeUpdate(create);
				User u1 = new User();
				u1.setUserId(max);
				u1.setUserName(name);
				u1.setUserNumber(contact);
//				req.setAttribute("user", u1);
//				RequestDispatcher rd=req.getRequestDispatcher("viewcreatedrecord.jsp");
//				rd.forward(req, resp);
//				pr = resp.getWriter();
//				pr.print(max + " " + name + " " + contact);
				resp.sendRedirect("index.jsp");

			}else if (val.equals("UPDATE")) {
				st.executeUpdate(update);
				resp.sendRedirect("index.jsp");
			} else if (val.equals("DELETE")) {
				st.executeUpdate(delete);
				resp.sendRedirect("index.jsp");
			}

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (con != null || st != null || rs != null || pr != null) {
				try {
					con.close();

				} catch (SQLException e) {
					e.printStackTrace();
				}
			}
		}

	}
}
